language: go

env:
  - tf_version=0.11.7

go:
  - 1.10.x

before_install:
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - make dep

script:
  - make all init validate

